version: '3'

services:
  restapi:
    build: ./api
    ports:
      - 5001:5000

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - api
    environment:
      BACKEND_ADDR: api
      BACKEND_PORT: 5000
