version: '3'

services:
    brevetsapp:
        build: brevetsapp/
        command: python -u flask_brevets.py
        ports:
            - "5687:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb

    restapi:
        build: api/
        command: python -u api.py
        ports:
            - "5688:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb

    website:
        build: api/
        command: python -u website.py
        ports:
            - "5689:5000"
        depends_on:
            - restapi
        environment:
            MONGODB_HOSTNAME: ourdb
            BACKEND_ADDR: api
            BACKEND_PORT: 5000
    ourdb:
        image: mongo:latest
